# fly.toml app configuration file generated for calebg-livebook on 2023-10-18T17:02:45-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "calebg-livebook"

[[mounts]]
  source = "livebook_data"
  destination = "/"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 8080
    handlers = ["tls", "http"]

[[metrics]]
